/*DROP TABLE IF EXISTS `TAN_DATASET`;*/
/*DROP TABLE IF EXISTS `TAN_DATASET_SEG`;*/
/*DROP TABLE IF EXISTS `TAN_DATASET_SEG_NEW`;*/
DROP TABLE IF EXISTS `TAN_DATASET_SEG_OP`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
/*CREATE TABLE `TAN_DATASET` (*/
/*CREATE TABLE `TAN_DATASET_SEG` (*/
CREATE TABLE `TAN_DATASET_SEG_OP` (
  `ROW_ID` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
/*`STUDY_CODE` varchar(12) NOT NULL,*/
  `IMAGE_ID` varchar(12) NOT NULL,
  `NOTE_TEXT` mediumtext,
  PRIMARY KEY (ROW_ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
